### ISSUE TITLE
Remote usage on headless Linux NAS server?

### ISSUE THREAD

**Issue by wechsler42** [netinvent/npbackup#31]
Hi there,
Thanks for providing this software to easier cope with Restic.
I have a question towards a possible usage scenario.
Is it possible, and if so how would I achieve this, to use npbackup on a headless Linux NAS server operating with the npbackup GUI from a remote PC?
Thanks in advance for a hint.

**Comment by deajan** [comment]
This will require a HTTP REST service for backup operations, and a separate GUI that will connect to the service.

I actually thought of such a tool since it would allow to resolve multiple problems with retention strategies for me.
But it's not planned this year.
I need to improve restic support before going that route.

**Comment by wechsler42** [comment]
Hello deajan,
thank you very much for considering my suggestion. I am looking forward on such a GUI!
