### ISSUE TITLE
Suggestion to improve Backup in progress bar

### ISSUE THREAD

**Issue by Xavron** [netinvent/npbackup#43]
I'm sure its current version is temporary, but on Windows 11, its always on top which is a bit of a problem. I just move it down to the right of the screen and that is really cool.

Which gave me the idea that it might be really nice as a Windows 11 notification. To me, this would be the first good use of notifications. Of course, Linux also has notifications. That's extra work though.

Might be even better with less work, just keeping it as it is, but showing it at the corner of the screen and in a little to get past the task bar (or whatever) and have a button on it to get rid of it. Still have it draggable and/or setting to choose the corner. It is actually really handy to have visible like this.

Something to think about :)

**Comment by deajan** [comment]
Well, that's a good idea.
Notifications cannot be used here since it would require plumbing through various OS supports, but a "close the progress bar" button is definitly a good idea for long backups.
Not a huge fan of putting the progress bar in a corner by default though, especially since multiscreen setups will have the progress bar placement weird depending on the setup.

The will be a new problem, since the GUI behind the progress bar will not accept user input until operation is finished, so it would be required to add a status message in that GUI with something along "operation X in progress for repo Y", so the user understands that the GUI isn't just waiting for user input.

**Comment by Xavron** [comment]
I guess there's no way to get it away from blocking the UI thread without major changes? Interesting.

**Comment by deajan** [comment]
That's not the point.
What would happen if main UI buttons aren't blocked, and you push backup button while another task is running. Makes no sense to allow that, since the only return you'll get is "busy doing something else".

**Comment by Xavron** [comment]
Block the buttons instead of the whole UI. But, we have a different viewpoint on things as is apparent.

You can keep this open or close it as you wish. I have nothing further to input on this :)

**Comment by deajan** [comment]
What's the purpose of a non blocked UI where you cannot push any button ?

Anyway, I've improved the backup progress bar into something I wanted, ie showing stdout and stderr from the runner, and from restic itself into the GUI progression window.
The progression window can now be minimized, which is what I expected in improving the bar.
![image](https://github.com/netinvent/npbackup/assets/4681318/f31ceb7e-2692-4488-850d-65aa59566b61)
