### ISSUE TITLE
npbackup-viewer with large number of snapshots is slow 

### ISSUE THREAD

**Issue by markft** [netinvent/npbackup#87]
It looks like the display of snapshots slows down based on the number of snapshots. The message "Runner took 1.25 seconds for snapshots" is displayed and is in the log quickly but the screen display is slow.  I ran this with strace and it looks like the query to the S3 repo does complete but trying to display them hangs with the process running at 100%, buttons are not responsive.

600 snapshots in the repo takes ~1 minute
800 snapshots in the repo takes ~5 minutes
1000 snapshots in the repo takes ~9 minutes

This works with RC3. I've tried with the pre-compiled binaries and compiling them myself.

**Comment by deajan** [comment]
Pretty sure that's because of the on the fly data polling. Could you run with `_DEBUG=True` env variable to make sure that's the reason please ?
I don't have a 900 snapshots repo to replicate easily the issue...

**Comment by deajan** [comment]
Any news on this one ?
Since I don't have a 900 snapshots repo, I thought of making a mock function which would return 900 fake snapshots, but that's some work.

**Comment by markft** [comment]
Sorry, I replied to the email and didn't realize I wasn't suppose to.

I've attached the log with debug output.  The gui populated the list after the 2nd gui_thread_runner.

I created a quick test data set with:
  mkdir test_npbackup
  cd test_npbackup
  for i in {0001..1000}; do mkdir $i; date > $i/junk; done
  for i in {0001..1000}; do echo $i; restic backup --host=nohost --tag $i /home/frenetteme/test_npbackup/$i; done
[npbackup_log.gz](https://github.com/user-attachments/files/16753461/npbackup_log.gz)

**Comment by deajan** [comment]
So this one was actually a bit hard to catch.
It's the GUI framework autoscroll function that tries to calculate the scroll position that takes ages with higher amounts of text to update...

I've nevertheless added a little cache function to call GUI updates once a second instead of once every new line returned by restic, so my code depends less on GUI responsiveness.

Would you mind to give current master a quick test run ?

**Comment by deajan** [comment]
>> I created a quick test data set with:
That was actually a brilliant idea, which I reused to do something alike.

showing snapshots should now be reasonably fast. I plan to release RC4 probably tomorrow.
I'd enjoy any feedback ;)

**Comment by markft** [comment]
This has fixed the time to list the snapshots:

2024-09-09 17:33:21,540 :: INFO :: Listing snapshots of repo external
2024-09-09 17:33:23,696 :: INFO :: Snapshots listed successfully
2024-09-09 17:33:23,696 :: INFO :: Runner took 2.163291 seconds for snapshots
2024-09-09 17:33:34,810 :: INFO :: Showing content of snapshot 6229bb18 in repo external
2024-09-09 17:43:21,390 :: INFO :: Successfuly listed snapshot 6229bb18 content
2024-09-09 17:43:21,391 :: INFO :: Runner took 586.587895 seconds for ls

During the "See content" build, the process took over 20GB of RSS memory then dropped down to 86MB to display the tree:

During the "ls"
frenett+  536506 97.4  3.6 20530940 19287568 pts/0 Sl+ 17:33   6:14 /cm/shared/userapps/scicomp/utils/bin/npbackup-viewer/npbackup/restic --json ls 6229bb18

After the tree window is displayed:
frenett+  536451  1.3  0.0 432080 86236 pts/0    Sl+  17:33   0:14 ./npbackup-viewer --log-file /tmp/mark.log

**Comment by deajan** [comment]
> During the "See content" build, the process took over 20GB of RSS memory then dropped down to 86MB to display the tree:

Guess your snapshots has 1M+ entries ?
I've known this since v2, and already tried to work around, but here I'm stuck with the GUI implementation.
I'll have a look again.

**Comment by markft** [comment]
This snapshot has 728 entries but there are 2099 snapshots in the repo. It looks like it builds a cache of all snapshots not just the one your working on. Reducing it to focus on the snapshot selected would greatly reduce the memory and time needed.

**Comment by deajan** [comment]
Thank you for reporting back. I've nevertheless investigated a bit more.

For one of my bigger sansphots with 200k files when doing a `restic ls` operation, loading the whole file tree in memory is definitly memory consuming, especially since we're dealing with json.

After changing the json library for something smarter, I could trim the memory usage to from 1035MB to 860MB (also time taken to convert restic str output to parseable output decreased from 25 sec to 7 sec).

| Program | Memory usage |
|----------|----------|
| restic 0.17.1 x64 windows | 67MB |
| NPBackup v3.0.0-rc5 CLI x64 windows | 289MB |
| NPBackup v3.0.0-rc5 GUI x64 windows (showing content) | 1035MB |
| NPBackup v3.0.0-rc5 GUI x64 windows with better json (showing content) | 860MB |

I've checked a bit more of the code. There's not much more place for optimization IMO, I've already been there.
I've noticed that I could gain another whopping 127MB by removing the folder / file icons from the tree, so I've decided to compress them even more (from 417 bytes to 252 bytes), but this doesn't yield any signifcant improvement, and removing them completly doesn't make sense. I'm really stuck with the GUI framework limits I guess.

I've also done a quick GUI framework swap for the wx and qt ports which are basically drop-in replacements, but they don't have the TreeData or don't have requirements met for elder python versions I need to support (I pledge to support old distros like rhel7).

So for now, I can yield a 17% memory size reduction, but that's it.
I'll have some tests before deploying this in the next release.

Agian, thanks for testing / reporting, always appreciated.

**Comment by deajan** [comment]
Played a bit with the garbage collector by explicitly deleting memory hungry variables after usage then calling the gc.
Actually makes things worse (+17MB).
I think I'm quite at the maximum I can achieve here.

I still could use an internal format that's more memory optimized than json (ie messagepack), but it would require massive plumbing and I'm not sure it's worth it.

The other solution is to keep the data in memory, and dynamically load gui data when expanding the tree, but that's also some pretty hard work which I'm not sure is the way to go too.

I'd like to task you to retest next release with the current memory optimization.

**Comment by deajan** [comment]
So I finally decided to plumb my code a little bit in order to use the internal data representation of msgspec library instead of plain json representation.

Here are my results:

| Program | Memory usage |
|----------|----------|
| NPBackup v3.0.0-rc5 GUI x64 windows vanilla | 1035MB |
| NPBackup v3.0.0-rc5 GUI x64 windows with msgspec json drop-in | 860MB | 
| NPBackup v3.0.0-rc5 GUI x64 windows with msgspec json drop-in and struct usage | 660MB | 
| NPBackup v3.0.0-rc5 GUI x64 windows with msgspec json drop-in, struct data representation and manual garbage collection | 648MB |

That's a 37% memory usage improvement,.

**Comment by deajan** [comment]
v3.0.0-rc6 with faster GUI implementation is now released.
